version: '3'

services:
  db:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: 'currencytrackeruser'
      POSTGRES_PASSWORD: 'root123'
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: 'redis-server --requirepass root123'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  setup:
    depends_on:
      - 'db'
    env_file:
      - '.env'

  app:
    depends_on:
      - 'db'
      - 'redis'
      - 'setup'
    env_file:
      - '.env'

  sidekiq:
    depends_on:
      - 'db'
      - 'redis'
    env_file:
      - '.env'

volumes:
  redis:
  db:
