version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
    command:
      - "--character-set-server=utf8"
      - "--innodb_log_buffer_size=32M"
      - "--innodb_log_file_size=80M"
      - "--max_allowed_packet=8M"
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'

  redis:
    image: 'redis:3.2-alpine'
    container_name: redis
    command: 'redis-server --requirepass root123'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  setup:
    depends_on:
      - 'db'
      - 'redis'
    env_file:
      - '.env'

  app:
    env_file:
      - '.env'

  sidekiq:
    env_file:
      - '.env'

volumes:
  redis:
  db:
