version: '3'

services:
  app:
    build: .
    command: 'bundle exec puma -C config/puma.rb'
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'

  sidekiq:
    build: .
    command: 'sidekiq -C config/sidekiq.yml.erb'
    volumes:
      - '.:/app'

  web:
    build:
      context: .
      dockerfile: 'Dockerfile-nginx'
    ports:
      - '80:80'
      - '443:443'
