FROM nginx:1.13.8-alpine

RUN apk add --update --no-cache bash

# establish where Nginx should look for files
ENV APP_ROOT /app

WORKDIR $APP_ROOT

RUN mkdir -p /var/log

COPY public $APP_ROOT/public/

COPY config/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]