version: '3'

services:
  setup:
    image: 'currencytracker:latest'
    command: "bundle exec rails db:create db:migrate db:seed"

  app:
    depends_on:
      - 'setup'
    image: 'currencytracker:latest'
    container_name: currencytracker_app
    command: 'bundle exec puma -C config/puma.rb'
    volumes:
      - '.:/app'
    ports:
      - "80:3000"

  sidekiq:
    depends_on:
      - 'setup'
    image: 'currencytracker:latest'
    container_name: sidekiq
    command: 'bundle exec sidekiq -C config/sidekiq.yml.erb'
    volumes:
      - '.:/app'
