version: '3'

services:
  setup:
    image: 'acrcurrencytracker.azurecr.io/currencytracker:latest'
    command: "bundle exec rails db:migrate"

  app:
    image: 'acrcurrencytracker.azurecr.io/currencytracker:latest'
    command: 'bundle exec puma -C config/puma.rb'
    volumes:
      - '.:/app'

  sidekiq:
    image: 'acrcurrencytracker.azurecr.io/currencytracker:latest'
    command: 'bundle exec sidekiq -C config/sidekiq.yml.erb'
    volumes:
      - '.:/app'

  web:
    image: 'acrcurrencytracker.azurecr.io/nginx:latest'
    ports:
      - '8080:80'
      - '443:443'
