---
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 10
  username: root
  password: root
  host: localhost
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: currencytracker_dev
  # url: <%= ENV['DATABASE_URL'].gsub('?', '_dev?') %>

test:
  <<: *default
  database: currencytracker_test
  # url: <%= ENV['DATABASE_URL'].gsub('?', '_test?') %>

production:
  url: <%= ENV['DATABASE_URL'] %>
