---
default: &default
  adapter: mysql2
  encoding: utf8
  port: 3306
  pool: 50
  timeout: 5000
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  # socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: currencytracker_development

test:
  <<: *default
  database: currencytracker_test

staging:
  <<: *default
  database: currencytracker_staging

preprod:
  <<: *default
  database: currencytracker_preprod

production:
  <<: *default
  database: currencytracker
