apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    application: rails
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    application: rails
