apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    application: nginx
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  selector:
    application: nginx
  
