apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
  labels:
    application: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      application: nginx
  template:
    metadata:
      labels:
        application: nginx
    spec:
      containers:
      - image: currencytracker.azurecr.io/nginx:latest
        name: nginx
        ports:
        - containerPort: 80
        - containerPort: 443
      restartPolicy: Always